export var demoJSON = {
  id: 1,
  nome: "Visitante",
  email: "DEMO@gmail.com",
  senha: "DEMO123",
  livros: [
    {
      id: 1,
      capa: "https://kanto.legiaodosherois.com.br/w414-h414-q95/wp-content/uploads/2015/12/8850bda4cbef1ce234f9fdad1fa717c9.png.webp",
      titulo: "Harry Potter",
      subTitulo: "e a Pedra Filosofal",
      generoPrincipal: "Fantasia",
      generoSecundario: "Aventura",
      sinopse:
        "Deveria ser um livro só para o público infanto-juvenil. Mas, no mundo inteiro, gente de idades variadas lê Harry Potter - um fenômeno da literatura mundial que desafia crenças e estimativas. Harry Potter é um garoto cujos pais, feiticeiros, foram assassinados por um poderosíssimo bruxo quando ele ainda era um bebê. Ele foi levado, então, para a casa dos tios que nada tinham a ver com o sobrenatural. Pelo contrário. Até os 10 anos, Harry foi uma espécie de gata borralheira: maltratado pelos tios, herdava roupas velhas do primo gorducho, tinha óculos remendados e era tratado como um estorvo.No dia de seu aniversário de 11 anos, entretanto, ele parece deslizar por um buraco sem fundo, como o de Alice no país das maravilhas, que o conduz a um mundo mágico. Descobre sua verdadeira história e seu destino: ser um aprendiz de feiticeiro até o dia em que terá que enfrentar a pior força do mal, o homem que assassinou seus pais. O menino de olhos verde, magricela e desengonçado, tão habituado à rejeição, descobre, também, que é um herói no universo dos magos. Potter fica sabendo que é a única pessoa a ter sobrevivido a um ataque do tal bruxo do mal e essa é a causa da marca em forma de raio que ele carrega na testa. Ele não é um garoto qualquer, ele sequer é um feiticeiro qualquer, ele é Harry Potter, símbolo de poder, resistência e um líder natural entre os sobrenaturais. A fábula, recheada de fantasmas, paredes que falam, caldeirões, sapos, unicórnios, dragões e gigantes, não é, entretanto, apenas um passatempo. Harry Potter conduz a discussões metafísicas, aborda o eterno confronto entre o bem e o mal, evidencia algumas mazelas da sociedade, como o preconceito, a divisão de classes através do dinheiro e do berço, a inveja, o egoísmo, a competitividade exacerbada, a busca pelo ideal - a necessidade de aprender, nem que seja à força, que a vida é feita de derrotas e vitórias e que isso é importante para a formação básica de um adulto.",
      paginasLidas: 104,
      paginasTotais: 208,
      rating: 0,
      completo: false,
    },
    {
      id: 2,
      capa: "https://www.gruponovoseculo.com.br/image/cache/catalog/capas-ns/pequeno-principe-480x672.png",
      titulo: "O Pequeno Príncipe",
      subTitulo: "",
      generoPrincipal: "Filosofia",
      generoSecundario: "",
      sinopse: "'Você se torna eternamente responsável por aquele que cativa'.A obra prima de Saint-Exupéry com quase cinquenta ilustrações originais do autor, numa tradução minuciosa baseada tanto na edição original americana quanto na versão francesa. Um livro encantador para crianças e adultos e uma das obras mais lidas de todo o mundo. Como explicar a adoção deste livro por povos tão variados, em tantos países de todos os continentes? Como explicar que ele seja lido sempre por tantos milhões e milhões de pessoas? Como explicar a atualidade deste livro traduzido em oitenta línguas diferentes? Como compreender que uma história aparentemente tão ingênua seja comovente para tantas pessoas?O Pequeno Príncipe devolve a cada um o mistério da infância. De repente retornam os sonhos. Reaparece a lembrança de questionamentos, desvelam-se incoerências acomodadas, quase já imperceptíveis na pressa do dia a dia. Voltam ao coração escondidas recordações. O reencontro, o homem-menino",
      paginasLidas: 136,
      paginasTotais: 136,
      rating: 5,
      completo: true,
    },
  ],
};
